Install libffi-dev
If this library is missing, nodepool installation will fail with:

    fatal error: ffi.h: No such file or directory

Signed-off-by: Mate Lakat <mate.lakat@citrix.com>